import { z } from "zod";

const tag = z.enum(["BUTTON", "SELECT", "INPUT", "TEXTAREA", "DIALOG", "BODY", "OTHER", "NONE"]);
export const clientDiagnosticSchema = z.object({
  event: z.enum(["error", "rejection", "resource-error", "fetch-failed", "offline", "online", "voice",
    "window-focus", "window-blur", "visibility", "select-pointer", "select-change", "control-focus", "dialog-close"]),
  token: z.string().max(100).optional(),
  route: z.string().max(500),
  pageId: z.string().uuid().optional(),
  sequence: z.number().int().nonnegative().optional(),
  requestId: z.string().uuid().optional(),
  buildId: z.string().regex(/^[\w-]{1,80}$/).optional(),
  status: z.number().int().min(0).max(599).optional(),
  line: z.number().int().min(0).max(10000000).optional(),
  column: z.number().int().min(0).max(10000000).optional(),
  voiceRun: z.number().int().nonnegative().optional(),
  state: z.enum(["idle", "starting", "active", "stopping"]).optional(),
  mode: z.enum(["dry", "test", "session"]).optional(),
  phase: z.enum(["start", "microphone-ready", "microphone-failed", "worklet-failed", "ready", "devices-failed",
    "vad-ready", "vad-fallback", "stop-flush", "stop-immediate", "disconnect", "stopped", "start-error-stale",
    "pcm-detach-done", "pcm-detach-failed", "track-stop-done", "track-stop-failed",
    "node-disconnect-done", "node-disconnect-failed", "vad-destroy-done", "vad-destroy-failed",
    "context-close-done", "context-close-failed", "socket-close-failed", "cleanup-slow"]).optional(),
  durationMs: z.number().int().nonnegative().optional(),
  errorType: z.enum(["Error", "NotAllowedError", "NotFoundError", "NotReadableError", "OverconstrainedError",
    "InvalidStateError", "AbortError", "NotSupportedError", "TypeError", "RangeError", "NetworkError"]).optional(),
  focused: z.boolean().optional(),
  visible: z.boolean().optional(),
  activeDisabled: z.boolean().optional(),
  disabled: z.boolean().optional(),
  activeTag: tag.optional(),
  targetTag: tag.optional(),
  controlIndex: z.number().int().min(-1).max(10000).optional(),
  dialogCount: z.number().int().min(0).max(100).optional(),
}).strict();
