const RETRY_DELAYS = [2_000, 5_000, 15_000, 30_000, 60_000];

const UI = {
  en: {
    windowTitle: "Telegram URL alerts",
    title: "Telegram URL alerts",
    subtitle: "Create a bot with BotFather, connect chats, and receive a new address when the Cloudflare URL changes.",
    stepCreate: "1. Create a bot",
    stepToken: "2. Register the token",
    stepChats: "3. Connect recipients",
    stepEnable: "4. Enable automatic alerts",
    botFatherHelp: "Open BotFather, send /newbot, choose a display name, then choose a username ending in bot.",
    openBotFather: "Open BotFather",
    copyNewBot: "Copy /newbot",
    existingBot: "Already have a bot? Continue with its token.",
    tokenLabel: "Bot token",
    tokenPlaceholder: "Paste the token issued by BotFather",
    verifyBot: "Verify bot",
    verifying: "Verifying…",
    verifiedBot: "Verified bot",
    tokenSecurity: "The token is encrypted with the operating system and is never shown again.",
    connectHelp: "Use a dedicated bot. For a private chat, press Start after Telegram opens. For a group, select the group and send the generated Start command.",
    connectPrivate: "Connect private chat",
    connectGroup: "Connect group",
    waitingPrivate: "Waiting for Start in the private chat…",
    waitingGroup: "Waiting for Start in the group…",
    pairingTimeout: "No matching Start command was received. Try connecting again.",
    recipients: "Connected recipients",
    noRecipients: "No recipients connected yet.",
    privateChat: "Private",
    groupChat: "Group",
    test: "Test",
    remove: "Remove",
    testSent: "Test alert sent.",
    autoLabel: "Automatically start and recover the Cloudflare tunnel",
    autoHelp: "The initial healthy URL and every replacement URL will be sent to all connected recipients.",
    quickTunnelNotice: "Quick Tunnel addresses are temporary. This feature redistributes a new address; it does not keep the same address.",
    close: "Close",
    back: "Back",
    next: "Next",
    copied: "Copied.",
    invalidToken: "The bot token could not be verified.",
    encryptionUnavailable: "Secure operating-system storage is unavailable, so the token was not saved.",
    webhookConflict: "This bot has a webhook configured. Remove the webhook or use a dedicated bot before connecting chats.",
    botRequired: "Verify a bot first.",
    recipientRequired: "Connect at least one recipient first.",
    genericError: "The request failed. Check the network and try again.",
    tunnelTelegram: "Telegram URL alerts…",
    tunnelStatusOff: "Status: off",
    tunnelStatusConnecting: "Status: connecting",
    tunnelStatusConnected: "Status: connected",
    tunnelStatusRecovering: "Status: recovering",
    tunnelStart: "Create Cloudflare public URL",
    tunnelCopy: "Copy public URL",
    tunnelOpen: "Open public URL in browser",
    tunnelStop: "Stop public tunnel",
    tunnelBinaryMissing: "cloudflared.exe is missing from the installation.",
    tunnelUrlTimeout: "A Cloudflare public URL was not received within 30 seconds.",
    tunnelHealthFailed: "The public URL health check failed.",
    tunnelExited: "cloudflared stopped",
    initialNotification: "Live Conference Translation public URL is ready.",
    changedNotification: "The Cloudflare public URL changed.",
    recoveringNotification: "The Cloudflare public URL is unavailable. Automatic recovery is in progress.",
    stoppedNotification: "The Cloudflare public URL is unavailable. Automatic recovery is off.",
    appStoppedNotification: "The application was closed. The Cloudflare public URL is no longer available.",
    notificationTime: "Notification time",
    testNotification: "Live Conference Translation Telegram alerts are working.",
  },
  ko: {
    windowTitle: "Telegram URL 알림",
    title: "Telegram URL 알림",
    subtitle: "BotFather로 봇을 만들고 채팅을 연결하면 Cloudflare 주소가 바뀔 때 새 주소를 받을 수 있습니다.",
    stepCreate: "1. 봇 만들기",
    stepToken: "2. 토큰 등록",
    stepChats: "3. 수신 채팅 연결",
    stepEnable: "4. 자동 알림 켜기",
    botFatherHelp: "BotFather를 열어 /newbot을 보내고 표시 이름을 정한 다음, bot으로 끝나는 사용자 이름을 등록하세요.",
    openBotFather: "BotFather 열기",
    copyNewBot: "/newbot 복사",
    existingBot: "이미 만든 봇이 있으면 해당 봇의 토큰으로 계속할 수 있습니다.",
    tokenLabel: "봇 토큰",
    tokenPlaceholder: "BotFather가 발급한 토큰을 붙여넣으세요",
    verifyBot: "봇 확인",
    verifying: "확인 중…",
    verifiedBot: "확인된 봇",
    tokenSecurity: "토큰은 운영체제 보안 저장소로 암호화되며 저장 후 다시 표시되지 않습니다.",
    connectHelp: "전용 봇 사용을 권장합니다. 개인 채팅은 Telegram이 열리면 시작을 누르세요. 그룹은 그룹을 고른 뒤 생성된 시작 명령을 보내세요.",
    connectPrivate: "개인 채팅 연결",
    connectGroup: "그룹 연결",
    waitingPrivate: "개인 채팅의 시작 명령을 기다리는 중…",
    waitingGroup: "그룹의 시작 명령을 기다리는 중…",
    pairingTimeout: "일치하는 시작 명령을 받지 못했습니다. 다시 연결해 주세요.",
    recipients: "연결된 수신 대상",
    noRecipients: "연결된 수신 대상이 없습니다.",
    privateChat: "개인",
    groupChat: "그룹",
    test: "테스트",
    remove: "삭제",
    testSent: "테스트 알림을 보냈습니다.",
    autoLabel: "Cloudflare 터널 자동 시작·복구",
    autoHelp: "처음 확인된 URL과 교체된 URL을 연결된 모든 수신 대상에 보냅니다.",
    quickTunnelNotice: "Quick Tunnel 주소는 임시입니다. 이 기능은 같은 주소를 유지하지 않고 새 주소를 다시 전달합니다.",
    close: "닫기",
    back: "이전",
    next: "다음",
    copied: "복사했습니다.",
    invalidToken: "봇 토큰을 확인하지 못했습니다.",
    encryptionUnavailable: "운영체제 보안 저장소를 사용할 수 없어 토큰을 저장하지 않았습니다.",
    webhookConflict: "이 봇에 webhook이 설정되어 있습니다. webhook을 제거하거나 전용 봇을 사용한 뒤 채팅을 연결하세요.",
    botRequired: "먼저 봇을 확인해 주세요.",
    recipientRequired: "수신 대상을 하나 이상 연결해 주세요.",
    genericError: "요청에 실패했습니다. 네트워크를 확인한 뒤 다시 시도해 주세요.",
    tunnelTelegram: "Telegram URL 알림…",
    tunnelStatusOff: "상태: 꺼짐",
    tunnelStatusConnecting: "상태: 연결 중",
    tunnelStatusConnected: "상태: 연결됨",
    tunnelStatusRecovering: "상태: 복구 중",
    tunnelStart: "Cloudflare 공개 URL 만들기",
    tunnelCopy: "공개 URL 복사",
    tunnelOpen: "공개 URL 브라우저에서 열기",
    tunnelStop: "공개 터널 종료",
    tunnelBinaryMissing: "설치 파일에서 cloudflared.exe를 찾지 못했습니다.",
    tunnelUrlTimeout: "Cloudflare 공개 URL을 30초 안에 받지 못했습니다.",
    tunnelHealthFailed: "공개 URL 상태 확인에 실패했습니다.",
    tunnelExited: "cloudflared가 종료되었습니다",
    initialNotification: "Live Conference Translation 공개 URL이 준비되었습니다.",
    changedNotification: "Cloudflare 공개 URL이 변경되었습니다.",
    recoveringNotification: "Cloudflare 공개 URL에 접속할 수 없습니다. 자동 복구를 진행하고 있습니다.",
    stoppedNotification: "Cloudflare 공개 URL 연결이 종료되었습니다. 자동 복구가 꺼져 있습니다.",
    appStoppedNotification: "애플리케이션이 종료되어 Cloudflare 공개 URL 연결도 종료되었습니다.",
    notificationTime: "알림 시각",
    testNotification: "Live Conference Translation Telegram 알림이 정상적으로 작동합니다.",
  },
  vi: {
    windowTitle: "Thông báo URL qua Telegram",
    title: "Thông báo URL qua Telegram",
    subtitle: "Tạo bot bằng BotFather, kết nối cuộc trò chuyện và nhận địa chỉ mới khi URL Cloudflare thay đổi.",
    stepCreate: "1. Tạo bot",
    stepToken: "2. Đăng ký token",
    stepChats: "3. Kết nối nơi nhận",
    stepEnable: "4. Bật thông báo tự động",
    botFatherHelp: "Mở BotFather, gửi /newbot, chọn tên hiển thị rồi chọn tên người dùng kết thúc bằng bot.",
    openBotFather: "Mở BotFather",
    copyNewBot: "Sao chép /newbot",
    existingBot: "Nếu đã có bot, hãy tiếp tục bằng token của bot đó.",
    tokenLabel: "Token bot",
    tokenPlaceholder: "Dán token do BotFather cấp",
    verifyBot: "Xác minh bot",
    verifying: "Đang xác minh…",
    verifiedBot: "Bot đã xác minh",
    tokenSecurity: "Token được mã hóa bằng kho bảo mật của hệ điều hành và sẽ không được hiển thị lại.",
    connectHelp: "Nên dùng bot riêng. Với trò chuyện riêng, hãy nhấn Bắt đầu sau khi Telegram mở. Với nhóm, chọn nhóm rồi gửi lệnh bắt đầu được tạo.",
    connectPrivate: "Kết nối trò chuyện riêng",
    connectGroup: "Kết nối nhóm",
    waitingPrivate: "Đang chờ lệnh bắt đầu trong trò chuyện riêng…",
    waitingGroup: "Đang chờ lệnh bắt đầu trong nhóm…",
    pairingTimeout: "Không nhận được lệnh bắt đầu phù hợp. Hãy thử kết nối lại.",
    recipients: "Nơi nhận đã kết nối",
    noRecipients: "Chưa có nơi nhận nào được kết nối.",
    privateChat: "Riêng tư",
    groupChat: "Nhóm",
    test: "Thử",
    remove: "Xóa",
    testSent: "Đã gửi thông báo thử.",
    autoLabel: "Tự động khởi động và khôi phục đường hầm Cloudflare",
    autoHelp: "URL hoạt động đầu tiên và mọi URL thay thế sẽ được gửi tới tất cả nơi nhận.",
    quickTunnelNotice: "Địa chỉ Quick Tunnel chỉ là tạm thời. Tính năng này gửi lại địa chỉ mới, không giữ nguyên địa chỉ.",
    close: "Đóng",
    back: "Quay lại",
    next: "Tiếp",
    copied: "Đã sao chép.",
    invalidToken: "Không thể xác minh token bot.",
    encryptionUnavailable: "Không có kho bảo mật của hệ điều hành nên token không được lưu.",
    webhookConflict: "Bot này đang dùng webhook. Hãy gỡ webhook hoặc dùng bot riêng trước khi kết nối cuộc trò chuyện.",
    botRequired: "Hãy xác minh bot trước.",
    recipientRequired: "Hãy kết nối ít nhất một nơi nhận.",
    genericError: "Yêu cầu thất bại. Hãy kiểm tra mạng và thử lại.",
    tunnelTelegram: "Thông báo URL qua Telegram…",
    tunnelStatusOff: "Trạng thái: tắt",
    tunnelStatusConnecting: "Trạng thái: đang kết nối",
    tunnelStatusConnected: "Trạng thái: đã kết nối",
    tunnelStatusRecovering: "Trạng thái: đang khôi phục",
    tunnelStart: "Tạo URL công khai Cloudflare",
    tunnelCopy: "Sao chép URL công khai",
    tunnelOpen: "Mở URL công khai trong trình duyệt",
    tunnelStop: "Dừng đường hầm công khai",
    tunnelBinaryMissing: "Không tìm thấy cloudflared.exe trong bản cài đặt.",
    tunnelUrlTimeout: "Không nhận được URL công khai Cloudflare trong 30 giây.",
    tunnelHealthFailed: "Kiểm tra trạng thái URL công khai thất bại.",
    tunnelExited: "cloudflared đã dừng",
    initialNotification: "URL công khai Live Conference Translation đã sẵn sàng.",
    changedNotification: "URL công khai Cloudflare đã thay đổi.",
    recoveringNotification: "URL công khai Cloudflare hiện không truy cập được. Đang tự động khôi phục.",
    stoppedNotification: "Kết nối URL công khai Cloudflare đã dừng. Tự động khôi phục đang tắt.",
    appStoppedNotification: "Ứng dụng đã đóng nên URL công khai Cloudflare không còn truy cập được.",
    notificationTime: "Thời gian thông báo",
    testNotification: "Thông báo Telegram của Live Conference Translation đang hoạt động.",
  },
  th: {
    windowTitle: "การแจ้งเตือน URL ทาง Telegram",
    title: "การแจ้งเตือน URL ทาง Telegram",
    subtitle: "สร้างบอตด้วย BotFather เชื่อมต่อแชต และรับที่อยู่ใหม่เมื่อ URL ของ Cloudflare เปลี่ยน",
    stepCreate: "1. สร้างบอต",
    stepToken: "2. ลงทะเบียนโทเค็น",
    stepChats: "3. เชื่อมต่อผู้รับ",
    stepEnable: "4. เปิดการแจ้งเตือนอัตโนมัติ",
    botFatherHelp: "เปิด BotFather ส่ง /newbot ตั้งชื่อที่แสดง แล้วตั้งชื่อผู้ใช้ที่ลงท้ายด้วย bot",
    openBotFather: "เปิด BotFather",
    copyNewBot: "คัดลอก /newbot",
    existingBot: "หากมีบอตแล้ว ให้ใช้โทเค็นของบอตนั้นต่อได้",
    tokenLabel: "โทเค็นบอต",
    tokenPlaceholder: "วางโทเค็นที่ BotFather ออกให้",
    verifyBot: "ตรวจสอบบอต",
    verifying: "กำลังตรวจสอบ…",
    verifiedBot: "บอตที่ตรวจสอบแล้ว",
    tokenSecurity: "โทเค็นถูกเข้ารหัสด้วยที่เก็บข้อมูลปลอดภัยของระบบปฏิบัติการและจะไม่แสดงอีก",
    connectHelp: "แนะนำให้ใช้บอตเฉพาะ แชตส่วนตัวให้กดเริ่มหลัง Telegram เปิด ส่วนกลุ่มให้เลือกกลุ่มแล้วส่งคำสั่งเริ่มที่สร้างไว้",
    connectPrivate: "เชื่อมต่อแชตส่วนตัว",
    connectGroup: "เชื่อมต่อกลุ่ม",
    waitingPrivate: "กำลังรอคำสั่งเริ่มในแชตส่วนตัว…",
    waitingGroup: "กำลังรอคำสั่งเริ่มในกลุ่ม…",
    pairingTimeout: "ไม่ได้รับคำสั่งเริ่มที่ตรงกัน โปรดลองเชื่อมต่ออีกครั้ง",
    recipients: "ผู้รับที่เชื่อมต่อแล้ว",
    noRecipients: "ยังไม่มีผู้รับที่เชื่อมต่อ",
    privateChat: "ส่วนตัว",
    groupChat: "กลุ่ม",
    test: "ทดสอบ",
    remove: "ลบ",
    testSent: "ส่งการแจ้งเตือนทดสอบแล้ว",
    autoLabel: "เริ่มและกู้คืน Cloudflare Tunnel อัตโนมัติ",
    autoHelp: "URL ที่ใช้งานได้ครั้งแรกและ URL ที่เปลี่ยนทุกครั้งจะถูกส่งให้ผู้รับทั้งหมด",
    quickTunnelNotice: "ที่อยู่ Quick Tunnel เป็นแบบชั่วคราว คุณสมบัตินี้ส่งที่อยู่ใหม่ ไม่ได้คงที่อยู่เดิม",
    close: "ปิด",
    back: "ย้อนกลับ",
    next: "ถัดไป",
    copied: "คัดลอกแล้ว",
    invalidToken: "ตรวจสอบโทเค็นบอตไม่ได้",
    encryptionUnavailable: "ไม่มีที่เก็บข้อมูลปลอดภัยของระบบปฏิบัติการ จึงไม่ได้บันทึกโทเค็น",
    webhookConflict: "บอตนี้ตั้งค่า webhook อยู่ โปรดลบ webhook หรือใช้บอตเฉพาะก่อนเชื่อมต่อแชต",
    botRequired: "โปรดตรวจสอบบอตก่อน",
    recipientRequired: "โปรดเชื่อมต่อผู้รับอย่างน้อยหนึ่งรายการ",
    genericError: "คำขอล้มเหลว โปรดตรวจสอบเครือข่ายแล้วลองอีกครั้ง",
    tunnelTelegram: "การแจ้งเตือน URL ทาง Telegram…",
    tunnelStatusOff: "สถานะ: ปิด",
    tunnelStatusConnecting: "สถานะ: กำลังเชื่อมต่อ",
    tunnelStatusConnected: "สถานะ: เชื่อมต่อแล้ว",
    tunnelStatusRecovering: "สถานะ: กำลังกู้คืน",
    tunnelStart: "สร้าง URL สาธารณะของ Cloudflare",
    tunnelCopy: "คัดลอก URL สาธารณะ",
    tunnelOpen: "เปิด URL สาธารณะในเบราว์เซอร์",
    tunnelStop: "หยุด Tunnel สาธารณะ",
    tunnelBinaryMissing: "ไม่พบ cloudflared.exe ในไฟล์ติดตั้ง",
    tunnelUrlTimeout: "ไม่ได้รับ URL สาธารณะของ Cloudflare ภายใน 30 วินาที",
    tunnelHealthFailed: "ตรวจสอบสถานะ URL สาธารณะไม่สำเร็จ",
    tunnelExited: "cloudflared หยุดทำงาน",
    initialNotification: "URL สาธารณะของ Live Conference Translation พร้อมแล้ว",
    changedNotification: "URL สาธารณะของ Cloudflare เปลี่ยนแล้ว",
    recoveringNotification: "ไม่สามารถเข้าถึง URL สาธารณะของ Cloudflare ได้ กำลังกู้คืนอัตโนมัติ",
    stoppedNotification: "การเชื่อมต่อ URL สาธารณะของ Cloudflare หยุดแล้ว และปิดการกู้คืนอัตโนมัติอยู่",
    appStoppedNotification: "แอปพลิเคชันปิดแล้ว จึงไม่สามารถใช้ URL สาธารณะของ Cloudflare ได้อีก",
    notificationTime: "เวลาแจ้งเตือน",
    testNotification: "การแจ้งเตือน Telegram ของ Live Conference Translation ทำงานปกติ",
  },
  si: {
    windowTitle: "Telegram URL දැනුම්දීම්",
    title: "Telegram URL දැනුම්දීම්",
    subtitle: "BotFather මගින් bot එකක් සාදා, කතාබස් සම්බන්ධ කර Cloudflare URL වෙනස් වූ විට නව ලිපිනය ලබාගන්න.",
    stepCreate: "1. Bot එකක් සාදන්න",
    stepToken: "2. Token එක ලියාපදිංචි කරන්න",
    stepChats: "3. ලබන්නන් සම්බන්ධ කරන්න",
    stepEnable: "4. ස්වයංක්‍රීය දැනුම්දීම් සක්‍රිය කරන්න",
    botFatherHelp: "BotFather විවෘත කර /newbot යවන්න, දර්ශන නාමයක් තෝරා bot යනුවෙන් අවසන් වන පරිශීලක නාමයක් තෝරන්න.",
    openBotFather: "BotFather විවෘත කරන්න",
    copyNewBot: "/newbot පිටපත් කරන්න",
    existingBot: "දැනටමත් bot එකක් තිබේ නම් එහි token එක භාවිතයෙන් ඉදිරියට යන්න.",
    tokenLabel: "Bot token",
    tokenPlaceholder: "BotFather ලබාදුන් token එක අලවන්න",
    verifyBot: "Bot එක තහවුරු කරන්න",
    verifying: "තහවුරු කරමින්…",
    verifiedBot: "තහවුරු කළ bot",
    tokenSecurity: "Token එක මෙහෙයුම් පද්ධතියේ ආරක්ෂිත ගබඩාවෙන් සංකේතනය වන අතර නැවත නොපෙන්වයි.",
    connectHelp: "වෙන් කළ bot එකක් භාවිතා කරන්න. පුද්ගලික කතාබස සඳහා Telegram විවෘත වූ පසු Start ඔබන්න. සමූහයක් සඳහා සමූහය තෝරා සාදන ලද start විධානය යවන්න.",
    connectPrivate: "පුද්ගලික කතාබස සම්බන්ධ කරන්න",
    connectGroup: "සමූහය සම්බන්ධ කරන්න",
    waitingPrivate: "පුද්ගලික කතාබසේ start විධානය බලා සිටී…",
    waitingGroup: "සමූහයේ start විධානය බලා සිටී…",
    pairingTimeout: "ගැළපෙන start විධානයක් නොලැබුණි. නැවත සම්බන්ධ කරන්න.",
    recipients: "සම්බන්ධ කළ ලබන්නන්",
    noRecipients: "තවම ලබන්නන් සම්බන්ධ කර නැත.",
    privateChat: "පුද්ගලික",
    groupChat: "සමූහය",
    test: "පරීක්ෂා කරන්න",
    remove: "ඉවත් කරන්න",
    testSent: "පරීක්ෂණ දැනුම්දීම යවන ලදී.",
    autoLabel: "Cloudflare tunnel ස්වයංක්‍රීයව ආරම්භ කර නැවත සම්බන්ධ කරන්න",
    autoHelp: "පළමු සාර්ථක URL එක සහ සෑම ප්‍රතිස්ථාපන URL එකක්ම සියලු ලබන්නන්ට යවයි.",
    quickTunnelNotice: "Quick Tunnel ලිපින තාවකාලිකයි. මෙය එකම ලිපිනය තබා නොගෙන නව ලිපිනය නැවත යවයි.",
    close: "වසන්න",
    back: "ආපසු",
    next: "ඊළඟ",
    copied: "පිටපත් කරන ලදී.",
    invalidToken: "Bot token එක තහවුරු කළ නොහැක.",
    encryptionUnavailable: "මෙහෙයුම් පද්ධතියේ ආරක්ෂිත ගබඩාව නොමැති බැවින් token එක සුරැකුවේ නැත.",
    webhookConflict: "මෙම bot එකට webhook එකක් සකසා ඇත. කතාබස් සම්බන්ධ කිරීමට පෙර එය ඉවත් කරන්න හෝ වෙන් කළ bot එකක් භාවිතා කරන්න.",
    botRequired: "පළමුව bot එක තහවුරු කරන්න.",
    recipientRequired: "අවම වශයෙන් එක් ලබන්නෙකු සම්බන්ධ කරන්න.",
    genericError: "ඉල්ලීම අසාර්ථකයි. ජාලය පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
    tunnelTelegram: "Telegram URL දැනුම්දීම්…",
    tunnelStatusOff: "තත්ත්වය: අක්‍රියයි",
    tunnelStatusConnecting: "තත්ත්වය: සම්බන්ධ වෙමින්",
    tunnelStatusConnected: "තත්ත්වය: සම්බන්ධයි",
    tunnelStatusRecovering: "තත්ත්වය: නැවත සම්බන්ධ වෙමින්",
    tunnelStart: "Cloudflare පොදු URL එක සාදන්න",
    tunnelCopy: "පොදු URL එක පිටපත් කරන්න",
    tunnelOpen: "පොදු URL එක බ්‍රවුසරයෙන් විවෘත කරන්න",
    tunnelStop: "පොදු tunnel එක නවත්වන්න",
    tunnelBinaryMissing: "ස්ථාපනය තුළ cloudflared.exe හමු නොවීය.",
    tunnelUrlTimeout: "තත්පර 30ක් තුළ Cloudflare පොදු URL එකක් නොලැබුණි.",
    tunnelHealthFailed: "පොදු URL සෞඛ්‍ය පරීක්ෂාව අසාර්ථකයි.",
    tunnelExited: "cloudflared නතර විය",
    initialNotification: "Live Conference Translation පොදු URL එක සූදානම්.",
    changedNotification: "Cloudflare පොදු URL එක වෙනස් වී ඇත.",
    recoveringNotification: "Cloudflare පොදු URL එකට පිවිසිය නොහැක. ස්වයංක්‍රීය ප්‍රතිසාධනය ක්‍රියාත්මකයි.",
    stoppedNotification: "Cloudflare පොදු URL සම්බන්ධතාව නතර වී ඇත. ස්වයංක්‍රීය ප්‍රතිසාධනය අක්‍රියයි.",
    appStoppedNotification: "යෙදුම වසා ඇති බැවින් Cloudflare පොදු URL එක තවදුරටත් ලබා ගත නොහැක.",
    notificationTime: "දැනුම් දුන් වේලාව",
    testNotification: "Live Conference Translation Telegram දැනුම්දීම් නිවැරදිව ක්‍රියා කරයි.",
  },
};

function stringsForLocale(locale) {
  const value = String(locale).toLowerCase();
  return UI[value.startsWith("ko") ? "ko" : value.startsWith("vi") ? "vi" : value.startsWith("th") ? "th" : value.startsWith("si") ? "si" : "en"];
}

function retryDelay(attempt) {
  return RETRY_DELAYS[Math.min(Math.max(attempt, 0), RETRY_DELAYS.length - 1)];
}

function shouldReplaceTunnel(localState, publicFailures) {
  return localState === "ours" && publicFailures >= 3;
}

function shouldNotifyTunnelStopped(reason, activeUrl, lastNotifiedUrl) {
  return reason !== "quit" && Boolean(activeUrl) && activeUrl === lastNotifiedUrl;
}

function shouldSendTelegramUrl(hasToken, chatCount, activeUrl, notificationUrl) {
  return Boolean(hasToken) && chatCount > 0 && activeUrl === notificationUrl;
}

function pairingChat(update, nonce, mode) {
  const message = update?.message;
  const chat = message?.chat;
  const expectedType = mode === "private" ? "private" : ["group", "supergroup"];
  const matchesType = Array.isArray(expectedType) ? expectedType.includes(chat?.type) : chat?.type === expectedType;
  const escaped = nonce.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (!matchesType || !new RegExp(`^/start(?:@\\w+)?\\s+${escaped}$`).test(message?.text ?? "")) return null;
  const title = chat.type === "private"
    ? [chat.first_name, chat.last_name].filter(Boolean).join(" ") || chat.username || String(chat.id)
    : chat.title || String(chat.id);
  return { id: String(chat.id), title, type: chat.type };
}

function notificationKey(chatId, url) {
  return `${chatId}\n${url}`;
}

module.exports = {
  notificationKey,
  pairingChat,
  retryDelay,
  shouldNotifyTunnelStopped,
  shouldReplaceTunnel,
  shouldSendTelegramUrl,
  stringsForLocale,
};
