const RETRY_DELAYS = [2_000, 5_000, 15_000, 30_000, 60_000];

const UI = {
  en: {
    windowTitle: "Telegram URL alerts",
    title: "Telegram URL alerts",
    subtitle: "Create a bot with BotFather, connect chats, and receive a new address when the Cloudflare URL changes.",
    stepCreate: "1. Create a bot",
    stepToken: "2. Register the token",
    stepChats: "3. Connect recipients",
    stepEnable: "4. Enable automatic alerts",
    botFatherHelp: "Open BotFather, send /newbot, choose a display name, then choose a username ending in bot.",
    openBotFather: "Open BotFather",
    copyNewBot: "Copy /newbot",
    existingBot: "Already have a bot? Continue with its token.",
    tokenLabel: "Bot token",
    tokenPlaceholder: "Paste the token issued by BotFather",
    verifyBot: "Verify bot",
    verifying: "Verifying…",
    verifiedBot: "Verified bot",
    tokenSecurity: "The token is stored encrypted and is never shown again.",
    connectHelp: "Use a dedicated bot. For a private chat, press Start after Telegram opens. For a group, select the group and send the generated Start command.",
    connectPrivate: "Connect private chat",
    connectGroup: "Connect group",
    waitingPrivate: "Waiting for Start in the private chat…",
    waitingGroup: "Waiting for Start in the group…",
    pairingTimeout: "No matching Start command was received. Try connecting again.",
    recipients: "Connected recipients",
    noRecipients: "No recipients connected yet.",
    privateChat: "Private",
    groupChat: "Group",
    test: "Test",
    remove: "Remove",
    testSent: "Test alert sent.",
    autoLabel: "Automatically start and recover the Cloudflare tunnel",
    autoHelp: "The initial healthy URL and every replacement URL will be sent to all connected recipients.",
    quickTunnelNotice: "Quick Tunnel addresses are temporary. This feature redistributes a new address; it does not keep the same address.",
    close: "Close",
    back: "Back",
    next: "Next",
    copied: "Copied.",
    invalidToken: "The bot token could not be verified.",
    encryptionUnavailable: "Secure operating-system storage is unavailable, so the token was not saved.",
    webhookConflict: "This bot has a webhook configured. Remove the webhook or use a dedicated bot before connecting chats.",
    botRequired: "Verify a bot first.",
    recipientRequired: "Connect at least one recipient first.",
    genericError: "The request failed. Check the network and try again.",
    appGuide: "Start app guide",
    siteManagement: "App management",
    tunnelTelegram: "Telegram URL alerts…",
    tunnelStatusOff: "Status: off",
    tunnelStatusConnecting: "Status: connecting",
    tunnelStatusConnected: "Status: connected",
    tunnelStatusRecovering: "Status: recovering",
    tunnelStart: "Create Cloudflare public URL",
    tunnelCopy: "Copy public URL",
    tunnelOpen: "Open public URL in browser",
    tunnelStop: "Stop public tunnel",
    tunnelBinaryMissing: "cloudflared.exe is missing from the installation.",
    tunnelUrlTimeout: "A Cloudflare public URL was not received within 30 seconds.",
    tunnelHealthFailed: "The public URL health check failed.",
    tunnelExited: "cloudflared stopped",
    initialNotification: "Live Conference Translation public URL is ready.",
    changedNotification: "The Cloudflare public URL changed.",
    recoveringNotification: "The Cloudflare public URL is unavailable. Automatic recovery is in progress.",
    stoppedNotification: "The Cloudflare public URL is unavailable. Automatic recovery is off.",
    appStoppedNotification: "The application was closed. The Cloudflare public URL is no longer available.",
    notificationTime: "Notification time",
    testNotification: "Live Conference Translation Telegram alerts are working.",
  },
  ko: {
    windowTitle: "Telegram URL 알림",
    title: "Telegram URL 알림",
    subtitle: "BotFather로 봇을 만들고 채팅을 연결하면 Cloudflare 주소가 바뀔 때 새 주소를 받을 수 있습니다.",
    stepCreate: "1. 봇 만들기",
    stepToken: "2. 토큰 등록",
    stepChats: "3. 수신 채팅 연결",
    stepEnable: "4. 자동 알림 켜기",
    botFatherHelp: "BotFather를 열어 /newbot을 보내고 표시 이름을 정한 다음, bot으로 끝나는 사용자 이름을 등록하세요.",
    openBotFather: "BotFather 열기",
    copyNewBot: "/newbot 복사",
    existingBot: "이미 만든 봇이 있으면 해당 봇의 토큰으로 계속할 수 있습니다.",
    tokenLabel: "봇 토큰",
    tokenPlaceholder: "BotFather가 발급한 토큰을 붙여넣으세요",
    verifyBot: "봇 확인",
    verifying: "확인 중…",
    verifiedBot: "확인된 봇",
    tokenSecurity: "토큰은 암호화해 저장하며 저장 후 다시 표시되지 않습니다.",
    connectHelp: "전용 봇 사용을 권장합니다. 개인 채팅은 Telegram이 열리면 시작을 누르세요. 그룹은 그룹을 고른 뒤 생성된 시작 명령을 보내세요.",
    connectPrivate: "개인 채팅 연결",
    connectGroup: "그룹 연결",
    waitingPrivate: "개인 채팅의 시작 명령을 기다리는 중…",
    waitingGroup: "그룹의 시작 명령을 기다리는 중…",
    pairingTimeout: "일치하는 시작 명령을 받지 못했습니다. 다시 연결해 주세요.",
    recipients: "연결된 수신 대상",
    noRecipients: "연결된 수신 대상이 없습니다.",
    privateChat: "개인",
    groupChat: "그룹",
    test: "테스트",
    remove: "삭제",
    testSent: "테스트 알림을 보냈습니다.",
    autoLabel: "Cloudflare 터널 자동 시작·복구",
    autoHelp: "처음 확인된 URL과 교체된 URL을 연결된 모든 수신 대상에 보냅니다.",
    quickTunnelNotice: "Quick Tunnel 주소는 임시입니다. 이 기능은 같은 주소를 유지하지 않고 새 주소를 다시 전달합니다.",
    close: "닫기",
    back: "이전",
    next: "다음",
    copied: "복사했습니다.",
    invalidToken: "봇 토큰을 확인하지 못했습니다.",
    encryptionUnavailable: "운영체제 보안 저장소를 사용할 수 없어 토큰을 저장하지 않았습니다.",
    webhookConflict: "이 봇에 webhook이 설정되어 있습니다. webhook을 제거하거나 전용 봇을 사용한 뒤 채팅을 연결하세요.",
    botRequired: "먼저 봇을 확인해 주세요.",
    recipientRequired: "수신 대상을 하나 이상 연결해 주세요.",
    genericError: "요청에 실패했습니다. 네트워크를 확인한 뒤 다시 시도해 주세요.",
    appGuide: "앱 설명 실행",
    siteManagement: "앱 관리",
    tunnelTelegram: "Telegram URL 알림…",
    tunnelStatusOff: "상태: 꺼짐",
    tunnelStatusConnecting: "상태: 연결 중",
    tunnelStatusConnected: "상태: 연결됨",
    tunnelStatusRecovering: "상태: 복구 중",
    tunnelStart: "Cloudflare 공개 URL 만들기",
    tunnelCopy: "공개 URL 복사",
    tunnelOpen: "공개 URL 브라우저에서 열기",
    tunnelStop: "공개 터널 종료",
    tunnelBinaryMissing: "설치 파일에서 cloudflared.exe를 찾지 못했습니다.",
    tunnelUrlTimeout: "Cloudflare 공개 URL을 30초 안에 받지 못했습니다.",
    tunnelHealthFailed: "공개 URL 상태 확인에 실패했습니다.",
    tunnelExited: "cloudflared가 종료되었습니다",
    initialNotification: "Live Conference Translation 공개 URL이 준비되었습니다.",
    changedNotification: "Cloudflare 공개 URL이 변경되었습니다.",
    recoveringNotification: "Cloudflare 공개 URL에 접속할 수 없습니다. 자동 복구를 진행하고 있습니다.",
    stoppedNotification: "Cloudflare 공개 URL 연결이 종료되었습니다. 자동 복구가 꺼져 있습니다.",
    appStoppedNotification: "애플리케이션이 종료되어 Cloudflare 공개 URL 연결도 종료되었습니다.",
    notificationTime: "알림 시각",
    testNotification: "Live Conference Translation Telegram 알림이 정상적으로 작동합니다.",
  },
  vi: {
    windowTitle: "Thông báo URL qua Telegram",
    title: "Thông báo URL qua Telegram",
    subtitle: "Tạo bot bằng BotFather, kết nối cuộc trò chuyện và nhận địa chỉ mới khi URL Cloudflare thay đổi.",
    stepCreate: "1. Tạo bot",
    stepToken: "2. Đăng ký token",
    stepChats: "3. Kết nối nơi nhận",
    stepEnable: "4. Bật thông báo tự động",
    botFatherHelp: "Mở BotFather, gửi /newbot, chọn tên hiển thị rồi chọn tên người dùng kết thúc bằng bot.",
    openBotFather: "Mở BotFather",
    copyNewBot: "Sao chép /newbot",
    existingBot: "Nếu đã có bot, hãy tiếp tục bằng token của bot đó.",
    tokenLabel: "Token bot",
    tokenPlaceholder: "Dán token do BotFather cấp",
    verifyBot: "Xác minh bot",
    verifying: "Đang xác minh…",
    verifiedBot: "Bot đã xác minh",
    tokenSecurity: "Token được lưu dưới dạng mã hóa và sẽ không được hiển thị lại.",
    connectHelp: "Nên dùng bot riêng. Với trò chuyện riêng, hãy nhấn Bắt đầu sau khi Telegram mở. Với nhóm, chọn nhóm rồi gửi lệnh bắt đầu được tạo.",
    connectPrivate: "Kết nối trò chuyện riêng",
    connectGroup: "Kết nối nhóm",
    waitingPrivate: "Đang chờ lệnh bắt đầu trong trò chuyện riêng…",
    waitingGroup: "Đang chờ lệnh bắt đầu trong nhóm…",
    pairingTimeout: "Không nhận được lệnh bắt đầu phù hợp. Hãy thử kết nối lại.",
    recipients: "Nơi nhận đã kết nối",
    noRecipients: "Chưa có nơi nhận nào được kết nối.",
    privateChat: "Riêng tư",
    groupChat: "Nhóm",
    test: "Thử",
    remove: "Xóa",
    testSent: "Đã gửi thông báo thử.",
    autoLabel: "Tự động khởi động và khôi phục đường hầm Cloudflare",
    autoHelp: "URL hoạt động đầu tiên và mọi URL thay thế sẽ được gửi tới tất cả nơi nhận.",
    quickTunnelNotice: "Địa chỉ Quick Tunnel chỉ là tạm thời. Tính năng này gửi lại địa chỉ mới, không giữ nguyên địa chỉ.",
    close: "Đóng",
    back: "Quay lại",
    next: "Tiếp",
    copied: "Đã sao chép.",
    invalidToken: "Không thể xác minh token bot.",
    encryptionUnavailable: "Không có kho bảo mật của hệ điều hành nên token không được lưu.",
    webhookConflict: "Bot này đang dùng webhook. Hãy gỡ webhook hoặc dùng bot riêng trước khi kết nối cuộc trò chuyện.",
    botRequired: "Hãy xác minh bot trước.",
    recipientRequired: "Hãy kết nối ít nhất một nơi nhận.",
    genericError: "Yêu cầu thất bại. Hãy kiểm tra mạng và thử lại.",
    appGuide: "Chạy hướng dẫn ứng dụng",
    siteManagement: "Quản lý ứng dụng",
    tunnelTelegram: "Thông báo URL qua Telegram…",
    tunnelStatusOff: "Trạng thái: tắt",
    tunnelStatusConnecting: "Trạng thái: đang kết nối",
    tunnelStatusConnected: "Trạng thái: đã kết nối",
    tunnelStatusRecovering: "Trạng thái: đang khôi phục",
    tunnelStart: "Tạo URL công khai Cloudflare",
    tunnelCopy: "Sao chép URL công khai",
    tunnelOpen: "Mở URL công khai trong trình duyệt",
    tunnelStop: "Dừng đường hầm công khai",
    tunnelBinaryMissing: "Không tìm thấy cloudflared.exe trong bản cài đặt.",
    tunnelUrlTimeout: "Không nhận được URL công khai Cloudflare trong 30 giây.",
    tunnelHealthFailed: "Kiểm tra trạng thái URL công khai thất bại.",
    tunnelExited: "cloudflared đã dừng",
    initialNotification: "URL công khai Live Conference Translation đã sẵn sàng.",
    changedNotification: "URL công khai Cloudflare đã thay đổi.",
    recoveringNotification: "URL công khai Cloudflare hiện không truy cập được. Đang tự động khôi phục.",
    stoppedNotification: "Kết nối URL công khai Cloudflare đã dừng. Tự động khôi phục đang tắt.",
    appStoppedNotification: "Ứng dụng đã đóng nên URL công khai Cloudflare không còn truy cập được.",
    notificationTime: "Thời gian thông báo",
    testNotification: "Thông báo Telegram của Live Conference Translation đang hoạt động.",
  },
  th: {
    windowTitle: "การแจ้งเตือน URL ทาง Telegram",
    title: "การแจ้งเตือน URL ทาง Telegram",
    subtitle: "สร้างบอตด้วย BotFather เชื่อมต่อแชต และรับที่อยู่ใหม่เมื่อ URL ของ Cloudflare เปลี่ยน",
    stepCreate: "1. สร้างบอต",
    stepToken: "2. ลงทะเบียนโทเค็น",
    stepChats: "3. เชื่อมต่อผู้รับ",
    stepEnable: "4. เปิดการแจ้งเตือนอัตโนมัติ",
    botFatherHelp: "เปิด BotFather ส่ง /newbot ตั้งชื่อที่แสดง แล้วตั้งชื่อผู้ใช้ที่ลงท้ายด้วย bot",
    openBotFather: "เปิด BotFather",
    copyNewBot: "คัดลอก /newbot",
    existingBot: "หากมีบอตแล้ว ให้ใช้โทเค็นของบอตนั้นต่อได้",
    tokenLabel: "โทเค็นบอต",
    tokenPlaceholder: "วางโทเค็นที่ BotFather ออกให้",
    verifyBot: "ตรวจสอบบอต",
    verifying: "กำลังตรวจสอบ…",
    verifiedBot: "บอตที่ตรวจสอบแล้ว",
    tokenSecurity: "โทเค็นถูกจัดเก็บแบบเข้ารหัสและจะไม่แสดงอีก",
    connectHelp: "แนะนำให้ใช้บอตเฉพาะ แชตส่วนตัวให้กดเริ่มหลัง Telegram เปิด ส่วนกลุ่มให้เลือกกลุ่มแล้วส่งคำสั่งเริ่มที่สร้างไว้",
    connectPrivate: "เชื่อมต่อแชตส่วนตัว",
    connectGroup: "เชื่อมต่อกลุ่ม",
    waitingPrivate: "กำลังรอคำสั่งเริ่มในแชตส่วนตัว…",
    waitingGroup: "กำลังรอคำสั่งเริ่มในกลุ่ม…",
    pairingTimeout: "ไม่ได้รับคำสั่งเริ่มที่ตรงกัน โปรดลองเชื่อมต่ออีกครั้ง",
    recipients: "ผู้รับที่เชื่อมต่อแล้ว",
    noRecipients: "ยังไม่มีผู้รับที่เชื่อมต่อ",
    privateChat: "ส่วนตัว",
    groupChat: "กลุ่ม",
    test: "ทดสอบ",
    remove: "ลบ",
    testSent: "ส่งการแจ้งเตือนทดสอบแล้ว",
    autoLabel: "เริ่มและกู้คืน Cloudflare Tunnel อัตโนมัติ",
    autoHelp: "URL ที่ใช้งานได้ครั้งแรกและ URL ที่เปลี่ยนทุกครั้งจะถูกส่งให้ผู้รับทั้งหมด",
    quickTunnelNotice: "ที่อยู่ Quick Tunnel เป็นแบบชั่วคราว คุณสมบัตินี้ส่งที่อยู่ใหม่ ไม่ได้คงที่อยู่เดิม",
    close: "ปิด",
    back: "ย้อนกลับ",
    next: "ถัดไป",
    copied: "คัดลอกแล้ว",
    invalidToken: "ตรวจสอบโทเค็นบอตไม่ได้",
    encryptionUnavailable: "ไม่มีที่เก็บข้อมูลปลอดภัยของระบบปฏิบัติการ จึงไม่ได้บันทึกโทเค็น",
    webhookConflict: "บอตนี้ตั้งค่า webhook อยู่ โปรดลบ webhook หรือใช้บอตเฉพาะก่อนเชื่อมต่อแชต",
    botRequired: "โปรดตรวจสอบบอตก่อน",
    recipientRequired: "โปรดเชื่อมต่อผู้รับอย่างน้อยหนึ่งรายการ",
    genericError: "คำขอล้มเหลว โปรดตรวจสอบเครือข่ายแล้วลองอีกครั้ง",
    appGuide: "เริ่มคู่มือแอป",
    siteManagement: "จัดการแอป",
    tunnelTelegram: "การแจ้งเตือน URL ทาง Telegram…",
    tunnelStatusOff: "สถานะ: ปิด",
    tunnelStatusConnecting: "สถานะ: กำลังเชื่อมต่อ",
    tunnelStatusConnected: "สถานะ: เชื่อมต่อแล้ว",
    tunnelStatusRecovering: "สถานะ: กำลังกู้คืน",
    tunnelStart: "สร้าง URL สาธารณะของ Cloudflare",
    tunnelCopy: "คัดลอก URL สาธารณะ",
    tunnelOpen: "เปิด URL สาธารณะในเบราว์เซอร์",
    tunnelStop: "หยุด Tunnel สาธารณะ",
    tunnelBinaryMissing: "ไม่พบ cloudflared.exe ในไฟล์ติดตั้ง",
    tunnelUrlTimeout: "ไม่ได้รับ URL สาธารณะของ Cloudflare ภายใน 30 วินาที",
    tunnelHealthFailed: "ตรวจสอบสถานะ URL สาธารณะไม่สำเร็จ",
    tunnelExited: "cloudflared หยุดทำงาน",
    initialNotification: "URL สาธารณะของ Live Conference Translation พร้อมแล้ว",
    changedNotification: "URL สาธารณะของ Cloudflare เปลี่ยนแล้ว",
    recoveringNotification: "ไม่สามารถเข้าถึง URL สาธารณะของ Cloudflare ได้ กำลังกู้คืนอัตโนมัติ",
    stoppedNotification: "การเชื่อมต่อ URL สาธารณะของ Cloudflare หยุดแล้ว และปิดการกู้คืนอัตโนมัติอยู่",
    appStoppedNotification: "แอปพลิเคชันปิดแล้ว จึงไม่สามารถใช้ URL สาธารณะของ Cloudflare ได้อีก",
    notificationTime: "เวลาแจ้งเตือน",
    testNotification: "การแจ้งเตือน Telegram ของ Live Conference Translation ทำงานปกติ",
  },
  si: {
    windowTitle: "Telegram URL දැනුම්දීම්",
    title: "Telegram URL දැනුම්දීම්",
    subtitle: "BotFather මගින් bot එකක් සාදා, කතාබස් සම්බන්ධ කර Cloudflare URL වෙනස් වූ විට නව ලිපිනය ලබාගන්න.",
    stepCreate: "1. Bot එකක් සාදන්න",
    stepToken: "2. Token එක ලියාපදිංචි කරන්න",
    stepChats: "3. ලබන්නන් සම්බන්ධ කරන්න",
    stepEnable: "4. ස්වයංක්‍රීය දැනුම්දීම් සක්‍රිය කරන්න",
    botFatherHelp: "BotFather විවෘත කර /newbot යවන්න, දර්ශන නාමයක් තෝරා bot යනුවෙන් අවසන් වන පරිශීලක නාමයක් තෝරන්න.",
    openBotFather: "BotFather විවෘත කරන්න",
    copyNewBot: "/newbot පිටපත් කරන්න",
    existingBot: "දැනටමත් bot එකක් තිබේ නම් එහි token එක භාවිතයෙන් ඉදිරියට යන්න.",
    tokenLabel: "Bot token",
    tokenPlaceholder: "BotFather ලබාදුන් token එක අලවන්න",
    verifyBot: "Bot එක තහවුරු කරන්න",
    verifying: "තහවුරු කරමින්…",
    verifiedBot: "තහවුරු කළ bot",
    tokenSecurity: "Token එක සංකේතනය කර ගබඩා කරන අතර නැවත නොපෙන්වයි.",
    connectHelp: "වෙන් කළ bot එකක් භාවිතා කරන්න. පුද්ගලික කතාබස සඳහා Telegram විවෘත වූ පසු Start ඔබන්න. සමූහයක් සඳහා සමූහය තෝරා සාදන ලද start විධානය යවන්න.",
    connectPrivate: "පුද්ගලික කතාබස සම්බන්ධ කරන්න",
    connectGroup: "සමූහය සම්බන්ධ කරන්න",
    waitingPrivate: "පුද්ගලික කතාබසේ start විධානය බලා සිටී…",
    waitingGroup: "සමූහයේ start විධානය බලා සිටී…",
    pairingTimeout: "ගැළපෙන start විධානයක් නොලැබුණි. නැවත සම්බන්ධ කරන්න.",
    recipients: "සම්බන්ධ කළ ලබන්නන්",
    noRecipients: "තවම ලබන්නන් සම්බන්ධ කර නැත.",
    privateChat: "පුද්ගලික",
    groupChat: "සමූහය",
    test: "පරීක්ෂා කරන්න",
    remove: "ඉවත් කරන්න",
    testSent: "පරීක්ෂණ දැනුම්දීම යවන ලදී.",
    autoLabel: "Cloudflare tunnel ස්වයංක්‍රීයව ආරම්භ කර නැවත සම්බන්ධ කරන්න",
    autoHelp: "පළමු සාර්ථක URL එක සහ සෑම ප්‍රතිස්ථාපන URL එකක්ම සියලු ලබන්නන්ට යවයි.",
    quickTunnelNotice: "Quick Tunnel ලිපින තාවකාලිකයි. මෙය එකම ලිපිනය තබා නොගෙන නව ලිපිනය නැවත යවයි.",
    close: "වසන්න",
    back: "ආපසු",
    next: "ඊළඟ",
    copied: "පිටපත් කරන ලදී.",
    invalidToken: "Bot token එක තහවුරු කළ නොහැක.",
    encryptionUnavailable: "මෙහෙයුම් පද්ධතියේ ආරක්ෂිත ගබඩාව නොමැති බැවින් token එක සුරැකුවේ නැත.",
    webhookConflict: "මෙම bot එකට webhook එකක් සකසා ඇත. කතාබස් සම්බන්ධ කිරීමට පෙර එය ඉවත් කරන්න හෝ වෙන් කළ bot එකක් භාවිතා කරන්න.",
    botRequired: "පළමුව bot එක තහවුරු කරන්න.",
    recipientRequired: "අවම වශයෙන් එක් ලබන්නෙකු සම්බන්ධ කරන්න.",
    genericError: "ඉල්ලීම අසාර්ථකයි. ජාලය පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
    appGuide: "යෙදුම් මාර්ගෝපදේශය අරඹන්න",
    siteManagement: "යෙදුම් කළමනාකරණය",
    tunnelTelegram: "Telegram URL දැනුම්දීම්…",
    tunnelStatusOff: "තත්ත්වය: අක්‍රියයි",
    tunnelStatusConnecting: "තත්ත්වය: සම්බන්ධ වෙමින්",
    tunnelStatusConnected: "තත්ත්වය: සම්බන්ධයි",
    tunnelStatusRecovering: "තත්ත්වය: නැවත සම්බන්ධ වෙමින්",
    tunnelStart: "Cloudflare පොදු URL එක සාදන්න",
    tunnelCopy: "පොදු URL එක පිටපත් කරන්න",
    tunnelOpen: "පොදු URL එක බ්‍රවුසරයෙන් විවෘත කරන්න",
    tunnelStop: "පොදු tunnel එක නවත්වන්න",
    tunnelBinaryMissing: "ස්ථාපනය තුළ cloudflared.exe හමු නොවීය.",
    tunnelUrlTimeout: "තත්පර 30ක් තුළ Cloudflare පොදු URL එකක් නොලැබුණි.",
    tunnelHealthFailed: "පොදු URL සෞඛ්‍ය පරීක්ෂාව අසාර්ථකයි.",
    tunnelExited: "cloudflared නතර විය",
    initialNotification: "Live Conference Translation පොදු URL එක සූදානම්.",
    changedNotification: "Cloudflare පොදු URL එක වෙනස් වී ඇත.",
    recoveringNotification: "Cloudflare පොදු URL එකට පිවිසිය නොහැක. ස්වයංක්‍රීය ප්‍රතිසාධනය ක්‍රියාත්මකයි.",
    stoppedNotification: "Cloudflare පොදු URL සම්බන්ධතාව නතර වී ඇත. ස්වයංක්‍රීය ප්‍රතිසාධනය අක්‍රියයි.",
    appStoppedNotification: "යෙදුම වසා ඇති බැවින් Cloudflare පොදු URL එක තවදුරටත් ලබා ගත නොහැක.",
    notificationTime: "දැනුම් දුන් වේලාව",
    testNotification: "Live Conference Translation Telegram දැනුම්දීම් නිවැරදිව ක්‍රියා කරයි.",
  },
};

const MANAGEMENT_UI = {
  "en": {
    "connections": "Current connections",
    "liveCounts": "Live",
    "staleCounts": "Updates paused / connecting",
    "countNotice": "Connections, not unique people. Each tab counts separately; admin and voice transport connections are excluded.",
    "inputCount": "Input",
    "outputCount": "Output",
    "combinedInputCount": "Combined input",
    "combinedCount": "Combined view",
    "captureCount": "Voice capture",
    "managePermission": "Allow management in this private chat",
    "manageHelp": "Only approved private chats can view session links and control tunnels. Groups receive URL alerts only. Send /help to the bot for instructions.",
    "menu": "Management menu",
    "help": "Help",
    "sessions": "Active sessions",
    "links": "Page links",
    "stats": "Connection status",
    "tunnel": "Cloudflare",
    "refresh": "Refresh",
    "previous": "Previous",
    "cancel": "Cancel",
    "confirmStop": "Confirm tunnel stop",
    "autoOn": "Enable automatic start / recovery",
    "autoOff": "Disable automatic start / recovery",
    "enabled": "On",
    "disabled": "Off",
    "noSessions": "No active sessions.",
    "sessionGone": "This session is closed or deleted. Refresh the session list.",
    "serverUnavailable": "Session data is unavailable. Open the app and use its embedded server; an independently running server cannot be inspected by this bot.",
    "unauthorized": "Management is not approved for this private chat. In the app, connect this private chat in Telegram settings and enable management permission. Groups receive alerts only.",
    "expired": "This button has expired or is no longer valid. Open /menu again.",
    "busy": "An operation is already running. Please wait.",
    "working": "Working…",
    "done": "Completed.",
    "unknown": "Unknown command. Use /help for available actions.",
    "pollingConflict": "Bot reception is paused because a webhook or another receiver is using this bot. Use a dedicated bot, resolve the conflict, then retry.",
    "retryReceiver": "Retry bot reception",
    "receiverReady": "Bot reception is running.",
    "receiverWaiting": "Bot reception is starting or reconnecting.",
    "stopWarning": "Stopping the tunnel disconnects external users and disables automatic start / recovery. Active sessions: {count}. This confirmation expires in 60 seconds.",
    "localOnly": "No healthy Cloudflare URL. These links use the app's selected address and may require the same LAN or VPN.",
    "noUrl": "No public URL is currently available.",
    "participantGuide": "Participant guide",
    "inputGuide": "Input guide",
    "helpText": "/start or /menu — open the management menu.\n/help — show this guide.\n\nActive sessions → choose a session → Page links or Connection status. Links include enabled language input/output pages, combined input/view and participant/input guides. Refresh to get the current address and counts; long lists have Previous/Next buttons.\n\nConnection status counts open page connections, not unique people. Multiple tabs count separately. Admin and additional voice transport connections are excluded; guide-page visits are not counted.\n\nCloudflare → view status/URL, create a URL, stop the tunnel, or enable/disable automatic start and recovery. Creating a URL keeps an existing healthy tunnel. Disabling automatic recovery keeps the current tunnel. Stopping requires confirmation and also disables automatic start/recovery; external users will disconnect. URL changes and interruptions are still sent to connected recipients.\n\nOnly private chats explicitly approved in the app can manage. Groups receive URL alerts only. The Electron app with its embedded server, or the standalone Node server, must remain running. Externally managed tunnels are controlled in their own runtime. The bot cannot create/edit/end/delete sessions, start the PC/app, or provide TTS.\n\nIf the bot does not respond: check the app is running, internet connectivity, bot token and receiver status in Telegram settings, and your private chat's management permission. Use a dedicated bot if a webhook or another receiver conflicts."
  },
  "ko": {
    "connections": "현재 접속 연결 수",
    "liveCounts": "실시간",
    "staleCounts": "갱신 중단 / 연결 중",
    "countNotice": "사람 수가 아닌 페이지 연결 수입니다. 여러 탭은 각각 집계하며 관리자·음성 전송용 추가 연결은 제외합니다.",
    "inputCount": "입력",
    "outputCount": "출력",
    "combinedInputCount": "통합 입력",
    "combinedCount": "통합 조회",
    "captureCount": "음성 수집",
    "managePermission": "이 개인 채팅의 관리 권한 허용",
    "manageHelp": "승인한 개인 채팅만 세션 링크 조회와 터널 제어가 가능합니다. 그룹은 URL 알림만 받습니다. 봇에 /help를 보내 사용법을 확인하세요.",
    "menu": "관리 메뉴",
    "help": "도움말",
    "sessions": "활성 세션",
    "links": "페이지 링크",
    "stats": "접속 현황",
    "tunnel": "Cloudflare",
    "refresh": "새로고침",
    "previous": "이전",
    "cancel": "취소",
    "confirmStop": "터널 종료 확인",
    "autoOn": "자동 시작·복구 켜기",
    "autoOff": "자동 시작·복구 끄기",
    "enabled": "켜짐",
    "disabled": "꺼짐",
    "noSessions": "활성 세션이 없습니다.",
    "sessionGone": "종료되거나 삭제된 세션입니다. 세션 목록을 새로고침해 주세요.",
    "serverUnavailable": "세션 정보를 조회할 수 없습니다. 앱과 앱의 내장 서버를 실행해 주세요. 별도로 실행된 서버는 봇에서 조회할 수 없습니다.",
    "unauthorized": "이 개인 채팅에는 관리 권한이 없습니다. 앱의 Telegram 설정에서 개인 채팅을 연결하고 관리 권한을 켜 주세요. 그룹은 알림 전용입니다.",
    "expired": "만료되었거나 사용할 수 없는 버튼입니다. /menu를 다시 열어 주세요.",
    "busy": "다른 작업을 처리 중입니다. 잠시 기다려 주세요.",
    "working": "처리 중…",
    "done": "완료했습니다.",
    "unknown": "알 수 없는 명령입니다. /help에서 가능한 작업을 확인해 주세요.",
    "pollingConflict": "webhook 또는 다른 수신 프로그램과 충돌해 봇 수신이 중단되었습니다. 전용 봇을 사용하고 충돌을 해결한 뒤 다시 연결해 주세요.",
    "retryReceiver": "봇 수신 다시 연결",
    "receiverReady": "봇 명령을 수신 중입니다.",
    "receiverWaiting": "봇 수신을 시작하거나 다시 연결하고 있습니다.",
    "stopWarning": "터널을 종료하면 외부 접속이 끊기고 자동 시작·복구도 꺼집니다. 활성 세션: {count}개. 확인 버튼은 60초 동안 유효합니다.",
    "localOnly": "정상 연결된 Cloudflare URL이 없습니다. 앱에서 선택한 공유 주소이며 같은 LAN 또는 VPN에서만 열릴 수 있습니다.",
    "noUrl": "현재 공개 URL이 없습니다.",
    "participantGuide": "참가자 안내",
    "inputGuide": "입력자 안내",
    "helpText": "/start 또는 /menu — 관리 메뉴를 엽니다.\n/help — 이 도움말을 표시합니다.\n\n활성 세션 → 세션 선택 → 페이지 링크 또는 접속 현황. 활성화된 언어별 입력·출력, 통합 입력·통합 조회, 참가자·입력자 안내 링크를 확인할 수 있습니다. 새로고침으로 현재 주소와 접속 수를 확인하고, 긴 목록은 이전·다음 버튼으로 이동합니다.\n\n접속 현황은 사람이 아닌 열린 페이지 연결 수입니다. 여러 탭은 각각 집계합니다. 관리자와 음성 전송용 추가 연결은 제외하며 안내 페이지 방문 수는 집계하지 않습니다.\n\nCloudflare → 상태·URL 조회, URL 생성, 터널 종료, 자동 시작·복구 켜기/끄기. URL 생성은 기존 정상 터널을 유지합니다. 자동 시작·복구 끄기는 현재 터널을 유지합니다. 터널 종료는 확인이 필요하며 자동 시작·복구도 끄고 외부 접속을 중단합니다. URL 변경과 연결 중단 알림은 기존 수신 대상에게 계속 보냅니다.\n\n앱에서 승인한 개인 채팅만 관리할 수 있고 그룹은 URL 알림 전용입니다. Electron 앱의 내장 서버 또는 독립 Node 서버가 실행 중이어야 합니다. 외부에서 관리하는 터널은 해당 실행 환경에서 제어합니다. 세션 생성·설정 변경·종료·삭제, PC·앱 원격 실행, TTS는 제공하지 않습니다.\n\n응답이 없으면 앱 실행·인터넷 연결, Telegram 설정의 봇 토큰·수신 상태, 개인 채팅의 관리 권한을 확인하세요. webhook이나 다른 수신 프로그램과 충돌하면 전용 봇을 사용해 주세요."
  },
  "vi": {
    "connections": "Kết nối hiện tại",
    "liveCounts": "Trực tiếp",
    "staleCounts": "Tạm dừng cập nhật / đang kết nối",
    "countNotice": "Đếm kết nối trang, không phải số người. Mỗi tab được tính riêng; loại trừ quản trị viên và kết nối truyền âm thanh bổ sung.",
    "inputCount": "Nhập",
    "outputCount": "Xuất",
    "combinedInputCount": "Nhập tổng hợp",
    "combinedCount": "Xem tổng hợp",
    "captureCount": "Thu âm",
    "managePermission": "Cho phép quản lý trong trò chuyện riêng này",
    "manageHelp": "Chỉ trò chuyện riêng được duyệt mới được xem liên kết phiên và điều khiển đường hầm. Nhóm chỉ nhận thông báo URL. Gửi /help để xem hướng dẫn.",
    "menu": "Menu quản lý",
    "help": "Trợ giúp",
    "sessions": "Phiên đang hoạt động",
    "links": "Liên kết trang",
    "stats": "Tình trạng kết nối",
    "tunnel": "Cloudflare",
    "refresh": "Làm mới",
    "previous": "Trước",
    "cancel": "Hủy",
    "confirmStop": "Xác nhận dừng đường hầm",
    "autoOn": "Bật tự khởi động / khôi phục",
    "autoOff": "Tắt tự khởi động / khôi phục",
    "enabled": "Bật",
    "disabled": "Tắt",
    "noSessions": "Không có phiên đang hoạt động.",
    "sessionGone": "Phiên đã kết thúc hoặc bị xóa. Hãy làm mới danh sách.",
    "serverUnavailable": "Không thể xem dữ liệu phiên. Hãy mở ứng dụng và máy chủ tích hợp; bot không thể kiểm tra máy chủ chạy riêng.",
    "unauthorized": "Trò chuyện riêng này chưa được cấp quyền. Hãy kết nối trò chuyện riêng và bật quyền quản lý trong cài đặt Telegram của ứng dụng. Nhóm chỉ nhận thông báo.",
    "expired": "Nút đã hết hạn hoặc không còn hợp lệ. Hãy mở lại /menu.",
    "busy": "Đang xử lý tác vụ khác. Vui lòng chờ.",
    "working": "Đang xử lý…",
    "done": "Đã hoàn tất.",
    "unknown": "Lệnh không xác định. Dùng /help để xem các thao tác.",
    "pollingConflict": "Đã tạm dừng nhận lệnh do xung đột webhook hoặc chương trình nhận khác. Dùng bot riêng, giải quyết xung đột rồi thử lại.",
    "retryReceiver": "Kết nối lại bộ nhận bot",
    "receiverReady": "Đang nhận lệnh bot.",
    "receiverWaiting": "Đang khởi động hoặc kết nối lại bộ nhận bot.",
    "stopWarning": "Dừng đường hầm sẽ ngắt người dùng bên ngoài và tắt tự khởi động / khôi phục. Phiên đang hoạt động: {count}. Xác nhận có hiệu lực 60 giây.",
    "localOnly": "Không có URL Cloudflare hoạt động. Các liên kết dùng địa chỉ được chọn trong ứng dụng và có thể cần cùng mạng LAN hoặc VPN.",
    "noUrl": "Hiện chưa có URL công khai.",
    "participantGuide": "Hướng dẫn người tham gia",
    "inputGuide": "Hướng dẫn người nhập",
    "helpText": "/start hoặc /menu — mở menu quản lý.\n/help — xem hướng dẫn này.\n\nPhiên đang hoạt động → chọn phiên → Liên kết trang hoặc Tình trạng kết nối. Xem các trang nhập/xuất theo ngôn ngữ được bật, nhập/xem tổng hợp và hướng dẫn người tham gia/người nhập. Làm mới để lấy địa chỉ và số kết nối hiện tại; dùng Trước/Tiếp cho danh sách dài.\n\nSố kết nối là số trang đang mở, không phải số người. Mỗi tab tính riêng. Loại trừ quản trị viên và kết nối truyền âm thanh bổ sung; không đếm lượt xem trang hướng dẫn.\n\nCloudflare → xem trạng thái/URL, tạo URL, dừng đường hầm, bật/tắt tự khởi động và khôi phục. Tạo URL giữ nguyên đường hầm đang hoạt động. Tắt tự khôi phục không dừng đường hầm hiện tại. Dừng cần xác nhận và cũng tắt tự khởi động/khôi phục; người dùng bên ngoài sẽ mất kết nối. Vẫn gửi thông báo URL thay đổi hoặc gián đoạn tới nơi nhận đã kết nối.\n\nChỉ trò chuyện riêng được duyệt trong ứng dụng mới được quản lý. Nhóm chỉ nhận thông báo URL. Ứng dụng Electron với máy chủ tích hợp hoặc máy chủ Node độc lập phải đang chạy. Đường hầm được quản lý bên ngoài phải được điều khiển tại môi trường chạy của nó. Bot không tạo/sửa/kết thúc/xóa phiên, không khởi động PC/ứng dụng và không có TTS.\n\nNếu không có phản hồi: kiểm tra ứng dụng, Internet, token và trạng thái nhận bot trong cài đặt Telegram, cùng quyền quản lý của trò chuyện riêng. Dùng bot riêng khi webhook hoặc bộ nhận khác gây xung đột."
  },
  "th": {
    "connections": "การเชื่อมต่อปัจจุบัน",
    "liveCounts": "เรียลไทม์",
    "staleCounts": "หยุดอัปเดต / กำลังเชื่อมต่อ",
    "countNotice": "นับการเชื่อมต่อหน้า ไม่ใช่จำนวนคน แต่ละแท็บนับแยก ไม่รวมผู้ดูแลและการเชื่อมต่อส่งเสียงเพิ่มเติม",
    "inputCount": "ป้อนข้อมูล",
    "outputCount": "ผลลัพธ์",
    "combinedInputCount": "ป้อนข้อมูลรวม",
    "combinedCount": "ดูข้อมูลรวม",
    "captureCount": "รับเสียง",
    "managePermission": "อนุญาตให้จัดการจากแชทส่วนตัวนี้",
    "manageHelp": "เฉพาะแชทส่วนตัวที่อนุมัติจึงดูลิงก์เซสชันและควบคุมทันเนลได้ กลุ่มรับเฉพาะแจ้งเตือน URL ส่ง /help เพื่อดูวิธีใช้",
    "menu": "เมนูจัดการ",
    "help": "วิธีใช้",
    "sessions": "เซสชันที่ใช้งาน",
    "links": "ลิงก์หน้า",
    "stats": "สถานะการเชื่อมต่อ",
    "tunnel": "Cloudflare",
    "refresh": "รีเฟรช",
    "previous": "ก่อนหน้า",
    "cancel": "ยกเลิก",
    "confirmStop": "ยืนยันหยุดทันเนล",
    "autoOn": "เปิดเริ่ม / กู้คืนอัตโนมัติ",
    "autoOff": "ปิดเริ่ม / กู้คืนอัตโนมัติ",
    "enabled": "เปิด",
    "disabled": "ปิด",
    "noSessions": "ไม่มีเซสชันที่ใช้งาน",
    "sessionGone": "เซสชันสิ้นสุดหรือถูกลบแล้ว โปรดรีเฟรชรายการ",
    "serverUnavailable": "ไม่สามารถดูข้อมูลเซสชันได้ โปรดเปิดแอปและเซิร์ฟเวอร์ในตัว บอตตรวจสอบเซิร์ฟเวอร์ที่ทำงานแยกไม่ได้",
    "unauthorized": "แชทส่วนตัวนี้ยังไม่มีสิทธิ์จัดการ โปรดเชื่อมต่อแชทส่วนตัวและเปิดสิทธิ์ในการตั้งค่า Telegram ของแอป กลุ่มรับเฉพาะแจ้งเตือน",
    "expired": "ปุ่มหมดอายุหรือใช้ไม่ได้แล้ว โปรดเปิด /menu อีกครั้ง",
    "busy": "กำลังดำเนินการอื่น โปรดรอ",
    "working": "กำลังดำเนินการ…",
    "done": "เสร็จแล้ว",
    "unknown": "ไม่รู้จักคำสั่ง ใช้ /help เพื่อดูสิ่งที่ทำได้",
    "pollingConflict": "หยุดรับคำสั่งเพราะ webhook หรือโปรแกรมรับอื่นขัดแย้งกัน ใช้บอตเฉพาะ แก้ไขแล้วลองใหม่",
    "retryReceiver": "เชื่อมต่อการรับบอตใหม่",
    "receiverReady": "กำลังรับคำสั่งบอต",
    "receiverWaiting": "กำลังเริ่มหรือเชื่อมต่อการรับบอตใหม่",
    "stopWarning": "การหยุดทันเนลจะตัดผู้ใช้ภายนอกและปิดเริ่ม / กู้คืนอัตโนมัติ เซสชันที่ใช้งาน: {count} การยืนยันมีอายุ 60 วินาที",
    "localOnly": "ไม่มี URL Cloudflare ที่ใช้งานได้ ลิงก์ใช้ที่อยู่ที่เลือกในแอปและอาจต้องใช้ LAN หรือ VPN เดียวกัน",
    "noUrl": "ยังไม่มี URL สาธารณะ",
    "participantGuide": "คู่มือผู้เข้าร่วม",
    "inputGuide": "คู่มือผู้ป้อนข้อมูล",
    "helpText": "/start หรือ /menu — เปิดเมนูจัดการ\n/help — แสดงวิธีใช้นี้\n\nเซสชันที่ใช้งาน → เลือกเซสชัน → ลิงก์หน้าหรือสถานะการเชื่อมต่อ ดูหน้าป้อน/แสดงผลตามภาษาที่เปิดใช้งาน หน้าป้อน/ดูข้อมูลรวม และคู่มือผู้เข้าร่วม/ผู้ป้อนข้อมูล รีเฟรชเพื่อดูที่อยู่และจำนวนล่าสุด ใช้ก่อนหน้า/ถัดไปสำหรับรายการยาว\n\nจำนวนการเชื่อมต่อคือหน้าที่เปิด ไม่ใช่จำนวนคน แต่ละแท็บนับแยก ไม่รวมผู้ดูแลและการเชื่อมต่อส่งเสียงเพิ่มเติม ไม่นับการเข้าหน้าคู่มือ\n\nCloudflare → ดูสถานะ/URL สร้าง URL หยุดทันเนล เปิด/ปิดเริ่มและกู้คืนอัตโนมัติ การสร้าง URL จะเก็บทันเนลที่ทำงานดีไว้ การปิดอัตโนมัติไม่หยุดทันเนลปัจจุบัน การหยุดต้องยืนยันและจะปิดเริ่ม/กู้คืนอัตโนมัติด้วย ผู้ใช้ภายนอกจะหลุด ยังส่งแจ้งเตือน URL เปลี่ยนและการขัดข้องให้ผู้รับที่เชื่อมต่อ\n\nเฉพาะแชทส่วนตัวที่อนุมัติในแอปจัดการได้ กลุ่มรับเฉพาะแจ้งเตือน URL แอป Electron พร้อมเซิร์ฟเวอร์ในตัวหรือเซิร์ฟเวอร์ Node แบบแยกต้องทำงานอยู่ ทันเนลภายนอกต้องควบคุมจากสภาพแวดล้อมที่รัน บอตสร้าง/แก้ไข/จบ/ลบเซสชัน เปิด PC/แอป หรือใช้ TTS ไม่ได้\n\nหากไม่มีการตอบกลับ ให้ตรวจว่าแอปทำงาน อินเทอร์เน็ต โทเค็นและสถานะรับบอตในการตั้งค่า Telegram และสิทธิ์แชทส่วนตัว หาก webhook หรือโปรแกรมอื่นขัดแย้ง ให้ใช้บอตเฉพาะ"
  },
  "si": {
    "connections": "වත්මන් සම්බන්ධතා",
    "liveCounts": "සජීවී",
    "staleCounts": "යාවත්කාලීන නතරයි / සම්බන්ධ වෙමින්",
    "countNotice": "ගණන් කරන්නේ පිටු සම්බන්ධතා මිස පුද්ගලයන් නොවේ. එක් එක් ටැබය වෙනම ගණන් කරයි. පරිපාලක සහ අමතර හඬ ප්‍රවාහ සම්බන්ධතා ඇතුළත් නොවේ.",
    "inputCount": "ආදාන",
    "outputCount": "ප්‍රතිදාන",
    "combinedInputCount": "ඒකාබද්ධ ආදාන",
    "combinedCount": "ඒකාබද්ධ දසුන",
    "captureCount": "හඬ ග්‍රහණය",
    "managePermission": "මෙම පෞද්ගලික කතාබහට කළමනාකරණ අවසර දෙන්න",
    "manageHelp": "අනුමත පෞද්ගලික කතාබහවලට පමණක් සැසි සබැඳි බැලීමට සහ tunnel පාලනයට හැක. කණ්ඩායම්වලට URL දැනුම්දීම් පමණි. උපදෙස් සඳහා /help යවන්න.",
    "menu": "කළමනාකරණ මෙනුව",
    "help": "උදව්",
    "sessions": "සක්‍රිය සැසි",
    "links": "පිටු සබැඳි",
    "stats": "සම්බන්ධතා තත්ත්වය",
    "tunnel": "Cloudflare",
    "refresh": "නැවුම් කරන්න",
    "previous": "පෙර",
    "cancel": "අවලංගු කරන්න",
    "confirmStop": "Tunnel නතර කිරීම තහවුරු කරන්න",
    "autoOn": "ස්වයංක්‍රීය ආරම්භය / ප්‍රතිසාධනය සක්‍රිය කරන්න",
    "autoOff": "ස්වයංක්‍රීය ආරම්භය / ප්‍රතිසාධනය අක්‍රිය කරන්න",
    "enabled": "සක්‍රියයි",
    "disabled": "අක්‍රියයි",
    "noSessions": "සක්‍රිය සැසි නැත.",
    "sessionGone": "සැසිය අවසන් කර හෝ මකා ඇත. ලැයිස්තුව නැවුම් කරන්න.",
    "serverUnavailable": "සැසි තොරතුරු ලබාගත නොහැක. යෙදුම සහ එහි අභ්‍යන්තර සේවාදායකය ක්‍රියාත්මක කරන්න. වෙනම ක්‍රියාත්මක සේවාදායකයක් බොට්ට පරීක්ෂා කළ නොහැක.",
    "unauthorized": "මෙම පෞද්ගලික කතාබහට අවසර නැත. යෙදුමේ Telegram සැකසුම් තුළ කතාබහ සම්බන්ධ කර කළමනාකරණ අවසර සක්‍රිය කරන්න. කණ්ඩායම් දැනුම්දීම් සඳහා පමණි.",
    "expired": "බොත්තම කල් ඉකුත් වී හෝ වලංගු නොවේ. /menu නැවත විවෘත කරන්න.",
    "busy": "වෙනත් කාර්යයක් ක්‍රියාත්මකයි. රැඳී සිටින්න.",
    "working": "සකසමින්…",
    "done": "සම්පූර්ණයි.",
    "unknown": "නොදන්නා විධානයකි. කළ හැකි දේ සඳහා /help බලන්න.",
    "pollingConflict": "webhook හෝ වෙනත් ග්‍රාහකයක් සමඟ ගැටුමක් නිසා බොට් විධාන ලබාගැනීම නතරයි. වෙන් කළ බොට් එකක් භාවිත කර ගැටුම විසඳා නැවත උත්සාහ කරන්න.",
    "retryReceiver": "බොට් ග්‍රාහකය නැවත සම්බන්ධ කරන්න",
    "receiverReady": "බොට් විධාන ලබාගනිමින්.",
    "receiverWaiting": "බොට් ග්‍රාහකය ආරම්භ කරමින් හෝ නැවත සම්බන්ධ වෙමින්.",
    "stopWarning": "Tunnel නතර කළ විට බාහිර පරිශීලකයන් විසන්ධි වන අතර ස්වයංක්‍රීය ආරම්භය / ප්‍රතිසාධනයත් අක්‍රිය වේ. සක්‍රිය සැසි: {count}. තහවුරු කිරීම තත්පර 60ක් වලංගුය.",
    "localOnly": "ක්‍රියාකාරී Cloudflare URL එකක් නැත. සබැඳි යෙදුමේ තෝරාගත් ලිපිනය භාවිත කරන අතර එකම LAN හෝ VPN අවශ්‍ය විය හැක.",
    "noUrl": "දැනට පොදු URL එකක් නැත.",
    "participantGuide": "සහභාගිවන්නන්ගේ මාර්ගෝපදේශය",
    "inputGuide": "ආදාන මාර්ගෝපදේශය",
    "helpText": "/start හෝ /menu — කළමනාකරණ මෙනුව විවෘත කරයි.\n/help — මෙම උපදෙස් පෙන්වයි.\n\nසක්‍රිය සැසි → සැසිය තෝරන්න → පිටු සබැඳි හෝ සම්බන්ධතා තත්ත්වය. සක්‍රිය භාෂා ආදාන/ප්‍රතිදාන, ඒකාබද්ධ ආදාන/දසුන සහ සහභාගිවන්නන්ගේ/ආදාන මාර්ගෝපදේශ බලන්න. වත්මන් ලිපිනය සහ ගණන් සඳහා නැවුම් කරන්න; දිගු ලැයිස්තුවල පෙර/ඊළඟ භාවිත කරන්න.\n\nසම්බන්ධතා ගණන යනු විවෘත පිටු ගණනයි, පුද්ගලයන් නොවේ. ටැබ් වෙනම ගණන් කරයි. පරිපාලක සහ අමතර හඬ ප්‍රවාහ සම්බන්ධතා ඉවත් කර ඇත; මාර්ගෝපදේශ පිටු බැලීම් ගණන් නොකරයි.\n\nCloudflare → තත්ත්වය/URL බලන්න, URL සාදන්න, tunnel නතර කරන්න, ස්වයංක්‍රීය ආරම්භය සහ ප්‍රතිසාධනය සක්‍රිය/අක්‍රිය කරන්න. URL සෑදීම දැනට ක්‍රියාකාරී tunnel එක තබා ගනී. ස්වයංක්‍රීය ක්‍රියාව අක්‍රිය කිරීම වත්මන් tunnel එක නතර නොකරයි. නතර කිරීමට තහවුරු කිරීම අවශ්‍යයි; එය ස්වයංක්‍රීය ආරම්භය/ප්‍රතිසාධනයත් අක්‍රිය කර බාහිර සම්බන්ධතා විසන්ධි කරයි. URL වෙනස්වීම් සහ බිඳවැටීම් දැනුම්දීම් දිගටම යවයි.\n\nයෙදුමේ අනුමත පෞද්ගලික කතාබහවලට පමණක් කළමනාකරණය කළ හැක. කණ්ඩායම්වලට URL දැනුම්දීම් පමණි. Electron සහ එහි සේවාදායකය හෝ වෙනම Node සේවාදායකය ක්‍රියාත්මක විය යුතුය. බාහිරව කළමනාකරණය වන උමං ඒවා ධාවනය වන පරිසරයෙන් පාලනය කරන්න. බොට්ට සැසි සෑදීම/වෙනස් කිරීම/අවසන් කිරීම/මැකීම, PC/යෙදුම ආරම්භ කිරීම හෝ TTS ලබාදීම කළ නොහැක.\n\nප්‍රතිචාර නැත්නම් යෙදුම, අන්තර්ජාලය, Telegram සැකසුම්වල ටෝකනය සහ ග්‍රාහක තත්ත්වය, පෞද්ගලික කතාබහේ අවසර බලන්න. webhook හෝ වෙනත් ග්‍රාහකයක් සමඟ ගැටුමක් ඇත්නම් වෙන් කළ බොට් එකක් භාවිත කරන්න."
  }
};

function stringsForLocale(locale) {
  const value = String(locale).toLowerCase();
  const lang = value.startsWith("ko") ? "ko" : value.startsWith("vi") ? "vi" : value.startsWith("th") ? "th" : value.startsWith("si") ? "si" : "en";
  return { ...UI[lang], ...MANAGEMENT_UI[lang] };
}

function retryDelay(attempt) {
  return RETRY_DELAYS[Math.min(Math.max(attempt, 0), RETRY_DELAYS.length - 1)];
}

function shouldReplaceTunnel(localState, publicFailures) {
  return localState === "ours" && publicFailures >= 3;
}

function shouldNotifyTunnelStopped(reason, activeUrl, lastNotifiedUrl) {
  return reason !== "quit" && Boolean(activeUrl) && activeUrl === lastNotifiedUrl;
}

function shouldSendTelegramUrl(hasToken, chatCount, activeUrl, notificationUrl) {
  return Boolean(hasToken) && chatCount > 0 && activeUrl === notificationUrl;
}

function pairingChat(update, nonce, mode) {
  const message = update?.message;
  const chat = message?.chat;
  const expectedType = mode === "private" ? "private" : ["group", "supergroup"];
  const matchesType = Array.isArray(expectedType) ? expectedType.includes(chat?.type) : chat?.type === expectedType;
  const escaped = nonce.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (!matchesType || !new RegExp(`^/start(?:@\\w+)?\\s+${escaped}$`).test(message?.text ?? "")) return null;
  const title = chat.type === "private"
    ? [chat.first_name, chat.last_name].filter(Boolean).join(" ") || chat.username || String(chat.id)
    : chat.title || String(chat.id);
  return { id: String(chat.id), title, type: chat.type };
}

function notificationKey(chatId, url) {
  return `${chatId}\n${url}`;
}

module.exports = {
  notificationKey,
  pairingChat,
  retryDelay,
  shouldNotifyTunnelStopped,
  shouldReplaceTunnel,
  shouldSendTelegramUrl,
  stringsForLocale,
};
